language: node_js
sudo: required
services:
- docker
node_js: 8
script: |
  npm run build &&
  docker build -t ${DOCKER_USER}/genie-logiciel .
after_success: |
  if [ "${TRAVIS_BRANCH}" == "master" ]; then
    docker login -u ${DOCKER_USER} -p ${DOCKER_PASS} && docker push ${DOCKER_USER}/genie-logiciel
  fi
notifications:
  email: false
deploy:
  provider: script
  skip_cleanup: true
  script: "curl -H 'Authorization: GitHub ${GITHUB_OAUTH_TOKEN}' -X POST https://dashboard-api.vibioh.fr/containers/cours/ --data-binary @docker-compose.yml"
