---

jobs:
  include:
    - stage: Build
      language: node_js
      node_js: 13
      services:
        - docker
      before_install:
        - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        - sudo apt-get update
        - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
        - echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
        - sudo systemctl restart docker
      script:
        - npm run reveal
        - npm run build
        - git --no-pager diff -- ':(exclude)www/js' ':(exclude)www/css' && git diff --quiet -- ':(exclude)www/js' ':(exclude)www/css'
        - sed -i -e "s|{{version}}|$(make version)|g" www/index.html
        - sed -i -e "s|{{version}}|$(make version)|g" www/js/index.js
        - sed -i -e "s|{{version}}|$(make version)|g" www/js/algolia.js
        - curl -q -sSL --max-time 10 "https://raw.githubusercontent.com/ViBiOh/scripts/master/bootstrap" | bash -s "release"
        - echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin
        - DOCKER_IMAGE="${DOCKER_USER}/l3miage" IMAGE_VERSION="$(make version)" ./scripts/release docker

    - stage: Publish

      language: minimal
      script:
        - curl -q -sSL --max-time 10 "https://raw.githubusercontent.com/ViBiOh/scripts/master/bootstrap" | bash -s "docker_promote"
        - scripts/docker_promote "${DOCKER_USER}/l3miage" "$(make version)"

    - stage: Index

      language: go
      go: 1.13
      script:
        - make
        - ./script/doc
        - ./script/index

stages:
  - Build
  - name: Publish
    if: branch = master && type = push
  - name: Index
    if: branch = master && type = push

notifications:
  email: false
