language: node_js
sudo: required
services:
- docker
node_js:
- 6.7.0
script:
- npm run build
- docker build -t ${DOCKER_USER}/genie-logiciel .
- docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
- docker push ${DOCKER_USER}/genie-logiciel
notifications:
  email: false
before_install:
- openssl aes-256-cbc -K $encrypted_afb3f4a0fd37_key -iv $encrypted_afb3f4a0fd37_iv -in deploy_rsa.enc -out deploy_rsa -d
before_deploy:
- eval "$(ssh-agent -s)"
- chmod 600 $TRAVIS_BUILD_DIR/deploy_rsa
- ssh-add $TRAVIS_BUILD_DIR/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: ssh -o StrictHostKeyChecking=no ${SSH_USER}@${SSH_HOST} "bash -s" 2>/dev/null -- < ./deploy.sh cours https://github.com/ViBiOh/md-genie-logiciel.git vibioh.fr
