version: '2'

services:
  site:
    image: vibioh/l3miage
    command:
    - -csp
    - default-src 'self'; base-uri 'self'; script-src 'self' 'unsafe-inline' cdn.jsdelivr.net/algoliasearch/3/; style-src 'self' 'unsafe-inline'; connect-src 'self' *.algolia.net *.algolianet.com; child-src www.youtube.com
    - -headers
    - X-UA-Compatible:ie=edge~content-language:fr
    - -env
    - ALGOLIA_APP,ALGOLIA_KEY,ALGOLIA_INDEX
    labels:
      traefik.frontend.passHostHeader: 'true'
      traefik.frontend.rule: 'Host: l3miage.fr, www.l3miage.fr'
      traefik.protocol: 'http'
      traefik.port: '1080'
      traefik.frontend.rateLimit.extractorFunc: 'client.ip'
      traefik.frontend.rateLimit.rateSet.first.period: '60s'
      traefik.frontend.rateLimit.rateSet.first.average: '100'
      traefik.frontend.rateLimit.rateSet.first.burst: '200'
    environment:
      ALGOLIA_APP: ${ALGOLIA_APP}
      ALGOLIA_KEY: ${ALGOLIA_KEY}
      ALGOLIA_INDEX: ${ALGOLIA_INDEX}
    restart: on-failure:5
    read_only: true
    cpu_shares: 128
    mem_limit: 67108864
    security_opt:
    - no-new-privileges
