version: '2'

services:
  site:
    image: vibioh/genie-logiciel
    command:
    - -spa
    - -csp
    - default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'
    labels:
      traefik.frontend.passHostHeader: 'true'
      traefik.frontend.rule: 'Host: l3miage.fr, www.l3miage.fr'
      traefik.port: '1080'
      traefik.backend.maxconn.amount: '16'
      traefik.backend.maxconn.extractorfunc: 'client.ip'
      traefik.frontend.rateLimit.extractorFunc: 'client.ip'
      traefik.frontend.rateLimit.rateSet.first.period: '60s'
      traefik.frontend.rateLimit.rateSet.first.average: '100'
      traefik.frontend.rateLimit.rateSet.first.burst: '200'
    logging:
      driver: json-file
      options:
        max-size: '10m'
    restart: on-failure:5
    read_only: true
    cpu_shares: 128
    mem_limit: 67108864
    security_opt:
    - no-new-privileges

networks:
  default:
    external:
      name: traefik
